Develop update plus IDF version 5 support (#73)
* Prepare for IDF version 5

* IDF v5 did not like that we use IoInterface

* BLE first try with 4 grays

* BLE correct nibbles

* Remove epdiy as REQUIRES component

* IDF v5 painful corrections. Also do not extend IoInterface otherwise: demo-sleep-clock-temp.cpp.obj: undefined reference to _ZTV11IoInterface

* Add demo IOs for https://www.tindie.com/stores/fasani/ CINWRITE

* CalEPD add new printerf

* #66 gdey073d46 Class working

* #66 Correct 7 color wifi download

* #62 IDF ver. 5 corrections

* #68 Start adding gdey0213b74

* #68 Optimize SPI sending whole row

* #68 Partial out but 50 pix y shifted

* #68 Start with 4 grays mode

* #68 GDEY0213 still searching for gray

* #68 gdey0213b74 0x22 Modes for gray

* #68 Add provisionary LUT for 4 gray mode in gdey0213b74

* New gdey0154d67 display implemented

* Add gdey0154d67 class

* gdey0154d67 remove full update LUT

* gdey0154d67 demo with SPI optimization (is 100ms faster)

* gdey0154d67 4 gray mode implemented

* #68 Add working 4 gray mode

* #68 Closer to get updateWindow working, my lord?

* #68 No way to fix updateWindow in 2nd get wrong Y

* Add new method available to all display.printerf("%x", args)

* #69 Add new class gdeq042Z21 based on gdew04Z21

* #70 gdey029T94 mono & 4 gray added

* #70 Getting better partial update

* #70 Get rotation right!

* #70 Fix also 4 gray mode

* #68 Fixes partial update for gdey0213b74

* gdey0154d67 partialWindow corrections but still comes out darkgray

* gdey0154d67 partialWindow fix gray update

* #71 Add goodisplay/gdey029T94

* Fixes after idf_v5 merge

* #66 Switch GDEY073D46 to use PSRAM

* Exclude parallel CPP classes if CALEPD_EXCLUDE_PARALLEL is defined

* Update new models removing rtc_wdt_feed

* Fix touch for IDF>=4.4

* #72 Get rid of Printable dependency

* #71 goodisplay/touch/gdey027T91T class

* Cleanup GDEW042T2, needs further Partial update corrections

* GDEW042T2 best waveform for partial update could find